services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.105.0
    command: ["--config=/etc/otelcol/otel-collector-config.yml"]
    ports:
      - "127.0.0.1:4317:4317"
      - "127.0.0.1:4318:4318"
      - "127.0.0.1:9464:9464"
    volumes:
      - ./otel-collector-config.yml:/etc/otelcol/otel-collector-config.yml:ro

